name: Set issue as waiting

on:
  issues:
    types: [opened]

jobs:
  label-waiting:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GH CLI
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
        run: |
          echo "$GH_TOKEN" | gh auth login --with-token

      - name: Add "Waiting for approbation" label
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue edit $ISSUE_NUMBER \
            --add-label "Waiting for approbation" \
            --repo "${{ github.repository }}"
